Possible fix for strange CacheControl filter issue seen by Gav & Ariel that I cannot reporduce myself. Current theories:
  [1]  Different filter config options makes filter
       called more than once, unexpectedly.

  [2]  Somewhat different versions of tomcat.

In any event, this seems like it should address a "can't happen" 
situation that apparently can, if [1] or [2] are causing the 
problem:

    SEVERE: Servlet.service() for servlet default threw exception
    java.lang.IllegalStateException: getWriter() has already been 
    called  for this response